### ISSUE TITLE
Incorrect hand strength calculation. 

### ISSUE THREAD

**Issue by alex-poliushkin** [spiritofsim/phe#1]
Hello! As per description "Bigger rank - better hand". 
I found that the assertion is not always true. Try this one:
```go
h1 := []pha.Card{pha.Cardas, pha.Cardad}
h2 := []pha.Card{pha.Card6h, pha.Card7h}
board := []pha.Card{
		pha.Cardjs,
		pha.Card8c,
		pha.Card8s,
		pha.Cardah,
		pha.Cardtc,
}

hand := append(board, h1...)
h1Rank, h1Type, _  := pha.Eval(
		ranks,
		hand...
)

hand[5] = h2[0]
hand[6] = h2[1]
h2Rank, h2Type, _  := pha.Eval(
	ranks,
	hand...
)

	log.Printf("hand1: type '%s', rank: %d", h1Type, h1Rank)
	log.Printf("hand2: type '%s', rank: %d", h2Type, h2Rank)
```
Result:
```
2019/07/08 12:33:29 hand1: type 'Full house', rank: 151
2019/07/08 12:33:29 hand2: type 'One pair', rank: 1521
```

I'm not sure why do we need this mask?
![code_snippet](https://user-images.githubusercontent.com/10319549/60800046-182b8500-a17d-11e9-8a18-fc7b310b2366.png)

**Comment by spiritofsim** [comment]
I fixed readme file. Of course you have to check hand type first.
I alse added hand struct with Compare method.
Also ranks are now loaded from embeded base64 const, so no need to load ranks from file

**Comment by spiritofsim** [comment]
Also there is now test for your case
